### ISSUE TITLE
Github is deprecating the set-output command

### ISSUE THREAD

**Issue by lorenries** [snaplet/action#2]
I'm getting a warning in my action that Github is deprecating the set-output command. Setting the database URL [here](https://github.com/snaplet/action/blob/main/action.yml#L55) should probably write to the `GITHUB_OUTPUT` environment variable.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by jgoux** [comment]
Hey @lorenries, is was fixed in the last release, thanks for reporting!
